[project]
name = 'p2p-microlending'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'
[contracts.mock-token-v0_0_1]
path = 'contracts/mock-token-v0_0_1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mzusd-engine-v1_0_0]
path = 'contracts/mzusd-engine-v1_0_0.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mzusd-engine-v1_1_0]
path = 'contracts/mzusd-engine-v1_1_0.clar'
clarity_version = 3
epoch = '3.2'

[contracts.mzusd-v1_0_0]
path = 'contracts/mzusd-v1_0_0.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
